### ISSUE TITLE
The edge module has not been pre-compiled for node.js version v14.4.0

### ISSUE THREAD

**Issue by susnick** [mike-eason/oledb#11]
Also tried 12.18.0. Had to go all the way back to 10.16.3 to get it working. Any plans to support later versions of node?

**Comment by keytrap-x86** [comment]
I just tried with 12.13.3 successfuly. What is the error you have ?

**Comment by tagoad** [comment]
Im resurrecting this in hopes of being able to use this package because its is the only thing I could find to interreact with Power Bi datasets. I have been trying to compile to 15.5.1, and I have been knocking the errors out with all the dependencies that edge-js has to build for 15.5.1, but I still get cannot open file 'MSCOREE.lib'. Any help with this would be greatly appreciated.

**Comment by mike-eason** [comment]
Hi guys, I must admit I haven't touched this project for a very long time, apologies for the delayed response. 

I have just had a go with `v14.17.1` and its all good here.

@tagoad Have you tried using the Node LTS?

**EDIT**: Hold up, I'll set up an environment in which to actually run the project and get back to you. I assumed this issue was occurring from an `npm install`.
